In [39]:
import numpy as  np
import gym
import random
import time
from IPython.display import clear_output

In [40]:
env = gym.make('FrozenLake-v1', is_slippery = False, map_name="8x8", render_mode="human")

In [41]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [42]:
total_episodes = 10000
max_steps = 100
learning_rate = 0.2
gamma = 0.99

epsilon = 1
max_epsilon = 1
min_epsilon = 0.01
decay_rate = 0.001

In [43]:
rewards = []

for episode in range(total_episodes):
    state, info = env.reset()
    step = 0
    done = False
    total_rewards = 0
    
    for step in range(max_steps):
        if random.uniform(0,1) > epsilon:
            action = np.argmax(q_table[state,:]) #Exploit
        else:
            action = env.action_space.sample() #Explore
            
        new_state, reward, done, truncated, info = env.step(action)
        
        max_new_state = np.max(q_table[new_state,:])
        
        q_table[state,action] = q_table[state,action] + learning_rate*(reward+gamma*max_new_state-q_table[state,action])
        
        total_rewards += reward
        
        state = new_state
        if done:
            break
        
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode)
    rewards.append(total_rewards)
        
print("Score:", str(sum(rewards)/total_episodes))

In [ ]:
print(q_table)

[[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.94917331]
 [0.83359385 0.970299   0.86229756 0.94115549]
 [0.93672043 0.         0.68339787 0.31692123]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.95341583]
 [0.         0.         0.         0.        ]
 [0.96059601 0.         0.970299   0.95099005]
 [0.96059601 0.9801     0.9801     0.        ]
 [0.970299   0.99       0.         0.970299  ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.98007631 0.99       0.97028739]
 [0.9801     0.99       1.         0.9801    ]
 [0.         0.         0.         0.        ]]


In [ ]:
import time

for episode in range(5):
    state,info = env.reset()
    step = 0
    done = False
    env.reset()

    
    print("Episode:", episode+1)
    
    for step in range(max_steps):
        action = np.argmax(q_table[state,:])
        new_state, reward, done, yruncated, info = env.step(action)
        env.render()
        time.sleep(0.1)
        if done:
            
            print("Number of Steps:", step)
            break
        state = new_state
        
env.close()

Episode: 1
Number of Steps: 5
Episode: 2
Number of Steps: 5
Episode: 3
Number of Steps: 5
Episode: 4
Number of Steps: 5
Episode: 5
Number of Steps: 5


NameError: name 'xvfb' is not defined